const $=id=>document.getElementById(id);let products=[],cart=JSON.parse(localStorage.getItem('dahaCart')||'[]'),category='';let token=localStorage.getItem('dahaToken');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function saveCart(){localStorage.setItem('dahaCart',JSON.stringify(cart));$('cartCount').textContent=cart.reduce((a,x)=>a+x.quantity,0)}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})};const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
async function load(){products=await api('/api/products');const cats=[...new Set(products.map(p=>p.category))];$('cats').innerHTML='<button class="'+(!category?'active':'')+'" onclick="setCat(\'\')">All</button>'+cats.map(c=>`<button class="${category===c?'active':''}" onclick="setCat('${esc(c)}')">${esc(c)}</button>`).join('');render()}
function render(){const q=($('search').value||'').toLowerCase();const list=products.filter(p=>(!category||p.category===category)&&(!q||p.name.toLowerCase().includes(q)));$('products').innerHTML=list.map(p=>`<article class="card"><div class="product-img">${p.image||'🛍️'}</div><div class="body"><div class="muted">${esc(p.category)} · ${esc(p.shop_name)}</div><h3>${esc(p.name)}</h3><p class="muted">${esc(p.description)}</p><div class="price">Rs. ${p.price.toLocaleString()}</div><button class="add" onclick="add(${p.id})">🛒 Add to Cart</button></div></article>`).join('')||'<div class="panel" style="padding:25px">No products found.</div>'}
function setCat(c){category=c;load()};$('search').oninput=render;
function add(id){const p=products.find(x=>x.id===id),old=cart.find(x=>x.productId===id);if(old)old.quantity++;else cart.push({productId:id,name:p.name,price:p.price,quantity:1});saveCart();alert('Added to cart');}
function openModal(html){$('modalbox').innerHTML=html;$('modal').classList.add('show')}function closeModal(){$('modal').classList.remove('show')}
function openCart(){const total=cart.reduce((a,x)=>a+x.price*x.quantity,0);openModal(`<button class="ghost" onclick="closeModal()">✕</button><h2>Your Cart</h2>${cart.length?cart.map((x,i)=>`<div class="panel" style="padding:12px;margin:8px 0"><b>${esc(x.name)}</b><br>Rs. ${x.price.toLocaleString()} × ${x.quantity}<button class="danger" style="float:right" onclick="removeCart(${i})">Remove</button></div>`).join(''):'<p>Your cart is empty.</p>'}<hr><h3>Total: Rs. ${total.toLocaleString()}</h3>${cart.length?'<button class="primary" style="width:100%" onclick="checkout()">Proceed to Checkout</button>':''}`)}
function removeCart(i){cart.splice(i,1);saveCart();openCart()}
function openAuth(){openModal(`<h2>Login</h2><label>Email</label><input id="aEmail" type="email"><label>Password</label><input id="aPass" type="password"><button class="primary" style="width:100%" onclick="login()">Login</button><hr><button class="ghost" onclick="registerCustomer()">Create Customer Account</button> <button class="ghost" onclick="openSellerRegister()">Become a Seller</button>`)}
async function login(){try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('aEmail').value,password:$('aPass').value})});token=d.token;localStorage.setItem('dahaToken',token);if(d.user.role==='seller')location.href='/seller.html';else if(d.user.role==='admin')location.href='/admin.html';else{closeModal();alert('Welcome '+d.user.name)}}catch(e){alert(e.message)}}
function registerCustomer(){openModal(`<h2>Create Customer Account</h2><label>Name</label><input id="rName"><label>Email</label><input id="rEmail" type="email"><label>Phone</label><input id="rPhone"><label>Password</label><input id="rPass" type="password"><button class="primary" style="width:100%" onclick="register('customer')">Create Account</button>`)}
function openSellerRegister(){openModal(`<h2>🏪 Seller Registration</h2><label>Your Name</label><input id="rName"><label>Email</label><input id="rEmail" type="email"><label>Phone</label><input id="rPhone"><label>Shop Name</label><input id="rShop"><label>Shop Address</label><textarea id="rAddress"></textarea><label>Password</label><input id="rPass" type="password"><button class="primary" style="width:100%" onclick="register('seller')">Create Seller Account</button><p class="small">New sellers start as pending and must be approved by admin.</p>`)}
async function register(role){try{const d=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:$('rName').value,email:$('rEmail').value,phone:$('rPhone').value,password:$('rPass').value,role,shopName:$('rShop')?.value,address:$('rAddress')?.value})});token=d.token;localStorage.setItem('dahaToken',token);if(role==='seller')location.href='/seller.html';else{closeModal();alert('Account created successfully')}}catch(e){alert(e.message)}}
function checkout(){if(!token){closeModal();openAuth();return}openModal(`<h2>Checkout</h2><label>Delivery Address</label><textarea id="oAddress"></textarea><label>Phone</label><input id="oPhone"><label>Payment Method</label><select id="oPay"><option value="COD">Cash on Delivery</option><option value="EasyPaisa">EasyPaisa</option><option value="JazzCash">JazzCash</option></select><button class="primary" style="width:100%" onclick="placeOrder()">Place Order</button>`)}
async function placeOrder(){try{const d=await api('/api/orders',{method:'POST',body:JSON.stringify({items:cart,address:$('oAddress').value,phone:$('oPhone').value,paymentMethod:$('oPay').value})});cart=[];saveCart();closeModal();alert('Order #'+d.orderId+' placed successfully.');}catch(e){alert(e.message)}}
$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};saveCart();load();
